
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: todo
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock


production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: todo
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *TEST
